### ISSUE TITLE
colors of patterns in p-strip--accent

### ISSUE THREAD

**Issue by pmahnke** [vanilla-framework/vanilla-brochure-theme#82]
## Process

1. place elements in .p-strip--accent, like buttons and p-card--highlighted

## Expected result

* colours of the text and backgrounds to invert or change

## Current result

* no change, and often the text is unreadable

## Screenshot

[If relevant, include a screenshot]

## Sample corrective code

```scss
  // XXX issue with colors for cards in a strip--accent
  .p-strip--accent {
    .p-card--highlighted {
      color: $color-mid-dark;

      a:link,
      a:visited {
        color: $color-brand;
      }

      a:hover,
      a:active {
        color: $color-brand;
        text-decoration: underline;
      }
    }
  }
```
